apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Constraints (instances of the CRDs created by ../templates). Requires those
# ConstraintTemplates to be established first.
resources:
  - require-non-root.yaml
  - require-resource-limits.yaml
  - disallow-latest-tag.yaml
  - require-hardened-container.yaml
  - require-probes.yaml
